#!/usr/bin/env python3

import sys
import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":
  for arg in sys.argv[1:]:
    data = np.loadtxt(arg)
    plt.loglog(data[:,0], data[:,1])
  plt.show()