#!/usr/bin/env python3

import sys
import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":

  fig, ax = plt.subplots(1,3, figsize=(12,3))
  
  for arg in sys.argv[1:]:
    data = np.loadtxt(arg)
    
    ax[0].plot(data[:,0], data[:,1])
    ax[1].semilogy(data[:,0], data[:,1])
    ax[2].loglog(data[:,0], data[:,1])
  
  plt.grid(True)
  plt.show()
